version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/go-assembly
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined